name: Feature request / Предложить идею
description: Suggest a new feature or an improvement / Новая функция или улучшение
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see? / Что хотите увидеть?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful? / Чем это полезно?
      description: Your use case / Как вы будете этим пользоваться
  - type: textarea
    id: extra
    attributes:
      label: Extra / Дополнительно
      description: Screenshots, links, similar mods / Скриншоты, ссылки, похожие моды
